FAYE_TOKEN = 'miauhash'
FAYE_CHANNEL_PREFIX = '/messagebox/'
FAYE_DEFAULT_CHANNEL = 'lobby'
FAYE_SERVER_PORT = 9292
FAYE_MOUNT_POINT = '/faye'
#FAYE_SERVER_URL = "http://192.168.0.100:#{FAYE_SERVER_PORT}#{FAYE_MOUNT_POINT}"
#FAYE_SERVER_URL = "http://localhost:#{FAYE_SERVER_PORT}#{FAYE_MOUNT_POINT}"
FAYE_SERVER_URL = "http://192.168.0.101:#{FAYE_SERVER_PORT}#{FAYE_MOUNT_POINT}"
