:output:
  User:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Admin:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Student:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Teacher:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Profile:
    :options:
      :fields:
      - firstname
      - lastname
      - codigo
      - user_id