:output:
  User:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Admin:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Student:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Teacher:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Technician:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Profile:
    :options:
      :fields:
      - id
      - firstname
      - lastname
      - codigo
      - user_id
  Device:
    :options:
      :fields:
      - id
      - name
      - tag
      - category
      - tipo
      - com
  Port:
    :options:
      :fields:
      - id
      - name
      - tag
      - device_id
  DeviceConnection:
    :options:
      :fields:
      - id
      - port_id
      - endpoint_id