:output:
  User:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Admin:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Student:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Teacher:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Technician:
    :options:
      :fields:
      - id
      - username
      - email
      - type
  Profile:
    :options:
      :fields:
      - id
      - firstname
      - lastname
      - codigo
      - user_id
  Dispositivo:
    :options:
      :fields:
      - id
      - nombre
      - etiqueta
      - categoria
      - tipo
      - estado
      - com
  Puerto:
    :options:
      :fields:
      - id
      - nombre
      - etiqueta
      - dispositivo_id
  DeviceConnection:
    :options:
      :fields:
      - id
      - puerto_id
      - endpoint_id