:output:
  User:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - options
  Admin:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - options
  Student:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - options
  Teacher:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - options
  Technician:
    :options:
      :fields:
      - id
      - username
      - email
      - type
      - options
  Profile:
    :options:
      :fields:
      - id
      - firstname
      - lastname
      - codigo
      - user_id
  Dispositivo:
    :options:
      :fields:
      - id
      - nombre
      - etiqueta
      - categoria
      - tipo
      - estado
      - status
      - cluster_id
      - com
  Puerto:
    :options:
      :fields:
      - id
      - nombre
      - etiqueta
      - dispositivo_id
      - numero
  DeviceConnection:
    :options:
      :fields:
      - id
      - puerto_id
      - endpoint_id
  Practica:
    :options:
      :fields:
      - id
      - name
      - estado
      - start
      - end
      - created_at